version: '3'

services:
  docker-svc-db:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5433:5433'
    volumes:
      - 'pgdata:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USERNAME=root'
      - 'POSTGRESQL_PASSWORD=root'
      - 'POSTGRESQL_DATABASE=docker_svc'

volumes:
  pgdata:
    driver: local