create:
	docker build --tag alpha-omega-corp/dockerfile-weee:latest .

tag:
	docker tag alpha-omega-corp/dockerfile-weee:latest ghcr.io/alpha-omega-corp/dockerfile-weee:latest

push:
	docker push ghcr.io/alpha-omega-corp/dockerfile-weee:latest